import "./globals.css";
import type { Metadata } from "next";
import Provider from "@/provider/Provider";
import Navbar from "@/Shared/Navbar";
import Footer from "@/Shared/Footer";

export const metadata: Metadata = {
  title: "Book App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-new-gr-c-s-check-loaded="14.1222.0"
      data-gr-ext-installed="">
      <body className={` bg-quaternary`}>
        <Provider>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
