import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/provider/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-new-gr-c-s-check-loaded="14.1222.0"
      data-gr-ext-installed="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-quaternary`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
